# Data configuration
data:
  data_dir: './data/videos/'
  annotations: './data/annotations/fps_multires_full_data.csv'
  train_ratio: 0.75
  subset_size: 1.0

# Model configuration
model:
  pretrained: True

# Training configuration
train:
  batch_size: 16
  epochs: 100
  lr: 0.0001
  weight_decay: 0.0005
  val_freq: 1
  use_amp: true
  warmup_ratio: 0.1 # onecycle warmup ratio
  num_workers: 8
  save_model: True

val:
    batch_size: 32

post_process:
  spatial_threshold: 30
  temporal_threshold: 8
  confidence_threshold: 0.99
  strategy: 'cluster_consolidate'
  mode: 'median'

# Loss parameters
loss:
  lambda_obj: 0.7 #2.0
  lambda_coord: 7.5
  lambda_noobj: 0.7 #2.0
  lambda_direction: 7.5
  lambda_temporal: 7.5 #7.0
  use_varifocal: False  # use varifocal loss to link confidence with localization quality
  varifocal_gamma: 2.0  # focusing parameter for hard examples (higher = more focus)
  varifocal_quality_scale: .25  # quality decay scale (higher = more lenient penality for predictions furhter from center)
  
# System configuration
system:
  seed: 42
  num_workers: 8
  device: 'cuda'

# Logging configuration
logging:
  log_dir: './logs'
  checkpoint_dir: './checkpoints'

# Evaluation configuration
eval:
  batch_size: 64
  confidence_threshold: 0.99
  consolidation_strategy: 'cluster_consolidate'
  pos_thresholds: [20]
  iou_thresholds: [0.5]
  angular_thresholds: [15]